#DMM-Auto Admin Coding Standard Checker tool
image: node:10.13.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install yarn
          - yarn add eslint@5.9.0
          - yarn add stylelint@9.2.1
          - yarn eslint
