export const FETCH_EXTERNAL_MEMBERS = 'project/FETCH_EXTERNAL_MEMBERS'
export const FETCH_EXTERNAL_MEMBERS_SUCCESS = 'project/FETCH_EXTERNAL_MEMBERS_SUCCESS'
export const REQUEST_ASSIGN_MEMBERS = 'project/REQUEST_ASSIGN_MEMBERS'
